tplatform :ios, '9.3'
target 'Smart_home' do
  pod 'FTPopOverMenu'
  pod 'BlurryModalSegue'
  pod 'AFNetworking'
  pod 'CocoaAsyncSocket'
  pod 'MBProgressHUD'
  pod 'MMDrawerController'
  pod 'CYLTableViewPlaceHolder'
  pod 'DCPathButton'
  pod 'pop'
  pod 'Bugly'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'AvoidCrash'
  pod 'JPush'
end
