platform :ios, '9.0'
target 'Smart_home' do
    pod 'FTPopOverMenu'
    pod 'BlurryModalSegue'
    pod 'AFNetworking'
    pod 'CocoaAsyncSocket'
    pod 'MBProgressHUD'
    pod 'MMDrawerController'
    pod 'CYLTableViewPlaceHolder'
    pod 'DCPathButton'
    pod 'Pgyer'
    pod 'PgyUpdate'
    pod 'pop'
    pod 'Bugly'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'IQKeyboardManager'
    pod 'AvoidCrash'
end
